CREATE TYPE "public"."attachment_kind" AS ENUM('prescripcion', 'autorizacion', 'dni', 'otros');--> statement-breakpoint
CREATE TYPE "public"."authorization_status" AS ENUM('no_aplica', 'pendiente', 'autorizada', 'rechazada');--> statement-breakpoint
CREATE TYPE "public"."order_origin" AS ENUM('ambulatorio', 'internacion', 'urgencia');--> statement-breakpoint
CREATE TYPE "public"."order_status" AS ENUM('borrador', 'confirmada', 'en_proceso', 'resultados_cargados', 'emitida', 'entregada', 'anulada');--> statement-breakpoint
CREATE TYPE "public"."patient_sex" AS ENUM('F', 'M', 'X');--> statement-breakpoint
CREATE TYPE "public"."payment_method" AS ENUM('efectivo', 'debito', 'credito', 'transferencia', 'mp', 'cuenta_corriente');--> statement-breakpoint
CREATE TYPE "public"."result_flag" AS ENUM('normal', 'low', 'high', 'critical_low', 'critical_high');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'recepcion', 'bioquimico');--> statement-breakpoint
CREATE TABLE "attachment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attachment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"kind" "attachment_kind" NOT NULL,
	"storage_path" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"uploaded_by" uuid NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"ip" "inet",
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "doctor" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "doctor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"matricula" text NOT NULL,
	"specialty" text,
	"phone" text,
	"email" text,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "insurer" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "insurer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"requires_authorization" boolean DEFAULT true NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "insurer_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "lab_config" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lab_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"legal_name" text NOT NULL,
	"cuit" text NOT NULL,
	"street_address" text NOT NULL,
	"city" text DEFAULT 'Santa Fe' NOT NULL,
	"province" text DEFAULT 'Santa Fe' NOT NULL,
	"phone" text,
	"email" text,
	"signing_professional_name" text NOT NULL,
	"signing_professional_mp" text NOT NULL,
	"signing_signature_path" text,
	"logo_url" text,
	"short_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"protocol_number" bigint DEFAULT nextval('seq_protocol') NOT NULL,
	"patient_id" bigint NOT NULL,
	"insurer_id" bigint NOT NULL,
	"insurance_affiliate_number" text,
	"referring_doctor_id" bigint,
	"referring_doctor_name" text,
	"referring_doctor_mp" text,
	"diagnosis" text,
	"origin" "order_origin" NOT NULL,
	"order_date" timestamp with time zone DEFAULT now() NOT NULL,
	"status" "order_status" DEFAULT 'borrador' NOT NULL,
	"is_urgent" boolean DEFAULT false NOT NULL,
	"notes" text,
	"total_particular" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"total_insurer" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"total_patient_copay" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"ub_value_used" numeric(12, 2) NOT NULL,
	"pdf_report_path" text,
	"pdf_report_issued_at" timestamp with time zone,
	"pdf_report_signed_by" uuid,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_practice" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_practice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"practice_id" bigint,
	"nbu_code_snapshot" text NOT NULL,
	"name_snapshot" text NOT NULL,
	"units_snapshot" numeric(8, 2) NOT NULL,
	"ub_value_snapshot" numeric(12, 2) NOT NULL,
	"price_particular" numeric(12, 2) NOT NULL,
	"price_insurer" numeric(12, 2) NOT NULL,
	"patient_copay" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"authorization_status" "authorization_status" DEFAULT 'no_aplica' NOT NULL,
	"authorization_code" text,
	"include_in_report" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patient" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dni" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"sex" "patient_sex",
	"birth_date" date NOT NULL,
	"phone" text,
	"email" text,
	"street_address" text,
	"city" text,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "payment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"method" "payment_method" NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"reference" text,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "practice" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nbu_code" text NOT NULL,
	"name" text NOT NULL,
	"short_name" text,
	"category" text,
	"section" text,
	"units" numeric(8, 2) NOT NULL,
	"requires_authorization" boolean DEFAULT false NOT NULL,
	"reference_value_template" jsonb,
	"is_special_act" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_practice_id" bigint NOT NULL,
	"value_numeric" numeric(20, 6),
	"value_text" text,
	"unit" text,
	"reference_range_low" numeric(20, 6),
	"reference_range_high" numeric(20, 6),
	"flag" "result_flag",
	"methodology" text,
	"notes" text,
	"entered_by" uuid NOT NULL,
	"entered_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_by" uuid,
	"reviewed_at" timestamp with time zone,
	CONSTRAINT "result_order_practice_id_unique" UNIQUE("order_practice_id")
);
--> statement-breakpoint
CREATE TABLE "ub_value" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ub_value_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"insurer_id" bigint NOT NULL,
	"valid_from" date NOT NULL,
	"valid_to" date,
	"value" numeric(12, 2) NOT NULL,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"display_name" text,
	"role" "user_role" NOT NULL,
	"matricula" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "attachment" ADD CONSTRAINT "attachment_order_id_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachment" ADD CONSTRAINT "attachment_uploaded_by_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_id_user_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doctor" ADD CONSTRAINT "doctor_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_patient_id_patient_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patient"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_insurer_id_insurer_id_fk" FOREIGN KEY ("insurer_id") REFERENCES "public"."insurer"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_referring_doctor_id_doctor_id_fk" FOREIGN KEY ("referring_doctor_id") REFERENCES "public"."doctor"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_pdf_report_signed_by_user_id_fk" FOREIGN KEY ("pdf_report_signed_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_practice" ADD CONSTRAINT "order_practice_order_id_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_practice" ADD CONSTRAINT "order_practice_practice_id_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practice"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient" ADD CONSTRAINT "patient_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment" ADD CONSTRAINT "payment_order_id_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment" ADD CONSTRAINT "payment_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_order_practice_id_order_practice_id_fk" FOREIGN KEY ("order_practice_id") REFERENCES "public"."order_practice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_entered_by_user_id_fk" FOREIGN KEY ("entered_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_reviewed_by_user_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ub_value" ADD CONSTRAINT "ub_value_insurer_id_insurer_id_fk" FOREIGN KEY ("insurer_id") REFERENCES "public"."insurer"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ub_value" ADD CONSTRAINT "ub_value_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_attachment_order" ON "attachment" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "idx_audit_actor_created" ON "audit_log" USING btree ("actor_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_entity" ON "audit_log" USING btree ("entity","entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_doctor_matricula_active" ON "doctor" USING btree ("matricula") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_doctor_lastname_trgm" ON "doctor" USING gin (last_name gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_order_protocol" ON "order" USING btree ("protocol_number");--> statement-breakpoint
CREATE INDEX "idx_order_patient_date" ON "order" USING btree ("patient_id","order_date");--> statement-breakpoint
CREATE INDEX "idx_order_status_date" ON "order" USING btree ("status","order_date");--> statement-breakpoint
CREATE INDEX "idx_order_practice_order" ON "order_practice" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_patient_dni_active" ON "patient" USING btree ("dni") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_patient_email" ON "patient" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_patient_lastname_trgm" ON "patient" USING gin (last_name gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_order" ON "payment" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_practice_nbucode" ON "practice" USING btree ("nbu_code");--> statement-breakpoint
CREATE INDEX "idx_practice_active_section" ON "practice" USING btree ("active","section");--> statement-breakpoint
CREATE INDEX "idx_practice_name_trgm" ON "practice" USING gin (name gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_ubvalue_current_per_insurer" ON "ub_value" USING btree ("insurer_id") WHERE valid_to IS NULL;