-- ============================================================================
-- 0004 — Multi-tenant (laboratorio + lab_id) + super role + preferencia_pdf
--        + unidades de medida dinámicas
--
-- IDEMPOTENTE: cada statement puede ejecutarse contra una DB que ya tiene
-- aplicados algunos o todos los cambios. Para dev (ya tiene casi todo via
-- db:push) es no-op para lo aplicado, y crea solo lo faltante. Para prod
-- (que no tiene NADA del delta), aplica todo en orden seguro: agrega columnas
-- nullable → backfill → set NOT NULL → agregar FK.
-- ============================================================================

-- ─── 1. Enum estado_lab ──────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE "public"."estado_lab" AS ENUM ('activo', 'suspendido', 'inactivo');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- ─── 2. user_role += 'super' ─────────────────────────────────────────────────
ALTER TYPE "public"."user_role" ADD VALUE IF NOT EXISTS 'super';
--> statement-breakpoint

-- ─── 3. Tabla laboratorio ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "laboratorio" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "laboratorio_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "slug" varchar(63) NOT NULL,
  "legal_name" text NOT NULL,
  "short_name" text,
  "cuit" text,
  "street_address" text,
  "city" text DEFAULT 'Santa Fe',
  "province" text DEFAULT 'Santa Fe',
  "phone" text,
  "email" text,
  "signing_professional_name" text,
  "signing_professional_mp" text,
  "signing_signature_path" text,
  "logo_path" text,
  "estado" "estado_lab" DEFAULT 'activo' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "laboratorio_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint

-- ─── 4. Bootstrap: laboratorio por defecto si la tabla está vacía ────────────
INSERT INTO "laboratorio" ("slug", "legal_name", "short_name", "estado")
  SELECT 'default', 'Laboratorio Principal', 'Lab', 'activo'
  WHERE NOT EXISTS (SELECT 1 FROM "laboratorio");
--> statement-breakpoint

-- ─── 5. lab_id en patient (data migration safe) ──────────────────────────────
DO $$
DECLARE default_lab_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='patient' AND column_name='lab_id') THEN
    SELECT id INTO default_lab_id FROM "laboratorio" ORDER BY id LIMIT 1;
    ALTER TABLE "patient" ADD COLUMN "lab_id" bigint;
    UPDATE "patient" SET "lab_id" = default_lab_id WHERE "lab_id" IS NULL;
    ALTER TABLE "patient" ALTER COLUMN "lab_id" SET NOT NULL;
  END IF;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "patient" ADD CONSTRAINT "patient_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DROP INDEX IF EXISTS "idx_patient_dni_active";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_patient_lab_dni_active"
  ON "patient" USING btree ("lab_id","dni") WHERE deleted_at IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_patient_lab" ON "patient" USING btree ("lab_id");
--> statement-breakpoint

-- ─── 6. lab_id en doctor ─────────────────────────────────────────────────────
DO $$
DECLARE default_lab_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='doctor' AND column_name='lab_id') THEN
    SELECT id INTO default_lab_id FROM "laboratorio" ORDER BY id LIMIT 1;
    ALTER TABLE "doctor" ADD COLUMN "lab_id" bigint;
    UPDATE "doctor" SET "lab_id" = default_lab_id WHERE "lab_id" IS NULL;
    ALTER TABLE "doctor" ALTER COLUMN "lab_id" SET NOT NULL;
  END IF;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "doctor" ADD CONSTRAINT "doctor_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DROP INDEX IF EXISTS "idx_doctor_matricula_active";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_doctor_lab_matricula_active"
  ON "doctor" USING btree ("lab_id","matricula") WHERE deleted_at IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_doctor_lab" ON "doctor" USING btree ("lab_id");
--> statement-breakpoint

-- ─── 7. lab_id en order ──────────────────────────────────────────────────────
DO $$
DECLARE default_lab_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='order' AND column_name='lab_id') THEN
    SELECT id INTO default_lab_id FROM "laboratorio" ORDER BY id LIMIT 1;
    ALTER TABLE "order" ADD COLUMN "lab_id" bigint;
    UPDATE "order" SET "lab_id" = default_lab_id WHERE "lab_id" IS NULL;
    ALTER TABLE "order" ALTER COLUMN "lab_id" SET NOT NULL;
  END IF;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "order" ADD CONSTRAINT "order_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_order_lab_status" ON "order" USING btree ("lab_id","status");
--> statement-breakpoint

-- ─── 8. lab_id en audit_log ──────────────────────────────────────────────────
DO $$
DECLARE default_lab_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='audit_log' AND column_name='lab_id') THEN
    SELECT id INTO default_lab_id FROM "laboratorio" ORDER BY id LIMIT 1;
    ALTER TABLE "audit_log" ADD COLUMN "lab_id" bigint;
    UPDATE "audit_log" SET "lab_id" = default_lab_id WHERE "lab_id" IS NULL;
    ALTER TABLE "audit_log" ALTER COLUMN "lab_id" SET NOT NULL;
  END IF;
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_audit_lab_created" ON "audit_log" USING btree ("lab_id","created_at");
--> statement-breakpoint

-- ─── 9. lab_id en user (nullable: super no pertenece a un lab) ───────────────
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "lab_id" bigint;
--> statement-breakpoint

DO $$
DECLARE default_lab_id bigint;
BEGIN
  -- Backfill solo para usuarios no-super que aún no tengan lab_id
  SELECT id INTO default_lab_id FROM "laboratorio" ORDER BY id LIMIT 1;
  UPDATE "user" SET "lab_id" = default_lab_id WHERE "lab_id" IS NULL AND "role" <> 'super';
END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "user" ADD CONSTRAINT "user_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

ALTER TABLE "user" DROP CONSTRAINT IF EXISTS "user_email_unique";
--> statement-breakpoint

-- ─── 10. preferencia_pdf ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "preferencia_pdf" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "preferencia_pdf_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "fondo_path" text,
  "layout_config" jsonb,
  "margin_top" integer DEFAULT 20 NOT NULL,
  "margin_bottom" integer DEFAULT 20 NOT NULL,
  "margin_left" integer DEFAULT 20 NOT NULL,
  "margin_right" integer DEFAULT 20 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "preferencia_pdf" ADD CONSTRAINT "preferencia_pdf_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_preferencia_pdf_lab" ON "preferencia_pdf" USING btree ("lab_id");
--> statement-breakpoint

-- ─── 11. unidad_medida ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "unidad_medida" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unidad_medida_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "nombre" text NOT NULL,
  "simbolo" text,
  "active" boolean DEFAULT true NOT NULL,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "unidad_medida" ADD CONSTRAINT "unidad_medida_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "unidad_medida" ADD CONSTRAINT "unidad_medida_created_by_user_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "public"."user"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_unidad_medida_lab_nombre" ON "unidad_medida" USING btree ("lab_id", lower("nombre"));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_unidad_medida_lab_active" ON "unidad_medida" USING btree ("lab_id","active");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_unidad_medida_nombre_trgm" ON "unidad_medida" USING gin (nombre gin_trgm_ops);
--> statement-breakpoint

-- ─── 12. practice_unidad ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "practice_unidad" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_unidad_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "practice_id" bigint NOT NULL,
  "unidad_id" bigint NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "practice_unidad" ADD CONSTRAINT "practice_unidad_lab_id_laboratorio_id_fk"
    FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "practice_unidad" ADD CONSTRAINT "practice_unidad_practice_id_practice_id_fk"
    FOREIGN KEY ("practice_id") REFERENCES "public"."practice"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "practice_unidad" ADD CONSTRAINT "practice_unidad_unidad_id_unidad_medida_id_fk"
    FOREIGN KEY ("unidad_id") REFERENCES "public"."unidad_medida"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_practice_unidad_unique" ON "practice_unidad" USING btree ("lab_id","practice_id","unidad_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_practice_unidad_lab_practice" ON "practice_unidad" USING btree ("lab_id","practice_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_practice_unidad_unidad" ON "practice_unidad" USING btree ("unidad_id");
--> statement-breakpoint

-- ─── 13. order_practice_unidad_value ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "order_practice_unidad_value" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_practice_unidad_value_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "order_practice_id" bigint NOT NULL,
  "unidad_id" bigint NOT NULL,
  "unidad_nombre_snapshot" text NOT NULL,
  "unidad_simbolo_snapshot" text,
  "value_numeric" numeric(20, 6),
  "value_text" text,
  "notes" text,
  "entered_by" uuid NOT NULL,
  "entered_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "order_practice_unidad_value" ADD CONSTRAINT "order_practice_unidad_value_order_practice_id_fk"
    FOREIGN KEY ("order_practice_id") REFERENCES "public"."order_practice"("id") ON DELETE cascade;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "order_practice_unidad_value" ADD CONSTRAINT "order_practice_unidad_value_unidad_id_fk"
    FOREIGN KEY ("unidad_id") REFERENCES "public"."unidad_medida"("id") ON DELETE restrict;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "order_practice_unidad_value" ADD CONSTRAINT "order_practice_unidad_value_entered_by_user_id_fk"
    FOREIGN KEY ("entered_by") REFERENCES "public"."user"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_op_unidad_value_unique" ON "order_practice_unidad_value" USING btree ("order_practice_id","unidad_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_op_unidad_value_op" ON "order_practice_unidad_value" USING btree ("order_practice_id");
