CREATE TYPE "public"."suscripcion_estado" AS ENUM('activa', 'cancelada');--> statement-breakpoint
CREATE TABLE "ciclo_consumo" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ciclo_consumo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"periodo" varchar(7) NOT NULL,
	"cupo_base" integer,
	"rollover" integer DEFAULT 0 NOT NULL,
	"usadas" integer DEFAULT 0 NOT NULL,
	"excedentes" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_ciclo_consumo_lab_periodo" UNIQUE("lab_id","periodo")
);
--> statement-breakpoint
CREATE TABLE "plan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" text NOT NULL,
	"cupo_ordenes_mes" integer NOT NULL,
	"precio_mensual" numeric(12, 2) NOT NULL,
	"precio_orden_excedente" numeric(12, 2) NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plan_nombre_unique" UNIQUE("nombre")
);
--> statement-breakpoint
CREATE TABLE "suscripcion" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suscripcion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"plan_id" bigint NOT NULL,
	"estado" "suscripcion_estado" DEFAULT 'activa' NOT NULL,
	"desde" timestamp with time zone DEFAULT now() NOT NULL,
	"hasta" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "es_excedente" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "ciclo_consumo" ADD CONSTRAINT "ciclo_consumo_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suscripcion" ADD CONSTRAINT "suscripcion_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suscripcion" ADD CONSTRAINT "suscripcion_plan_id_plan_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plan"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_suscripcion_unica_activa" ON "suscripcion" USING btree ("lab_id") WHERE estado = 'activa';