CREATE TYPE "public"."contrato_estado" AS ENUM('enviado', 'firmado', 'vencido', 'anulado');--> statement-breakpoint
CREATE TABLE "contrato" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contrato_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" varchar(64) NOT NULL,
	"estado" "contrato_estado" DEFAULT 'enviado' NOT NULL,
	"razon_social" text NOT NULL,
	"nombre_contacto" text NOT NULL,
	"cuit" text,
	"email_firmante" text NOT NULL,
	"telefono" text,
	"propuesta" jsonb NOT NULL,
	"plan_sugerido_id" bigint,
	"plan_elegido_id" bigint,
	"lab_creado_id" bigint,
	"datos_facturacion" jsonb,
	"expira_at" timestamp with time zone NOT NULL,
	"pdf_original_path" text,
	"pdf_firmado_path" text,
	"pdf_hash_sha256" text,
	"otp_hash" text,
	"otp_expira_at" timestamp with time zone,
	"otp_intentos" integer DEFAULT 0 NOT NULL,
	"otp_verificado_at" timestamp with time zone,
	"evidencia" jsonb,
	"firmado_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "contrato_token_unique" UNIQUE("token")
);
--> statement-breakpoint
ALTER TABLE "contrato" ADD CONSTRAINT "contrato_plan_sugerido_id_plan_id_fk" FOREIGN KEY ("plan_sugerido_id") REFERENCES "public"."plan"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contrato" ADD CONSTRAINT "contrato_plan_elegido_id_plan_id_fk" FOREIGN KEY ("plan_elegido_id") REFERENCES "public"."plan"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contrato" ADD CONSTRAINT "contrato_lab_creado_id_laboratorio_id_fk" FOREIGN KEY ("lab_creado_id") REFERENCES "public"."laboratorio"("id") ON DELETE set null ON UPDATE no action;