CREATE TYPE "public"."reunion_estado" AS ENUM('confirmada', 'cancelada');--> statement-breakpoint
CREATE TABLE "reunion" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reunion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" text NOT NULL,
	"email" text NOT NULL,
	"empresa" text,
	"telefono" text,
	"mensaje" text,
	"slot_inicio" timestamp with time zone NOT NULL,
	"slot_fin" timestamp with time zone NOT NULL,
	"estado" "reunion_estado" DEFAULT 'confirmada' NOT NULL,
	"google_event_id" text,
	"meet_link" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "reunion_slot_inicio_confirmada_idx" ON "reunion" USING btree ("slot_inicio") WHERE estado = 'confirmada';