CREATE TYPE "public"."anuncio_tipo" AS ENUM('info', 'advertencia', 'mantenimiento');--> statement-breakpoint
CREATE TYPE "public"."movimiento_tipo" AS ENUM('cargo', 'pago');--> statement-breakpoint
CREATE TABLE "anuncio" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anuncio_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mensaje" text NOT NULL,
	"tipo" "anuncio_tipo" DEFAULT 'info' NOT NULL,
	"lab_id" bigint,
	"activo" boolean DEFAULT true NOT NULL,
	"desde" timestamp with time zone,
	"hasta" timestamp with time zone,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "lab_movimiento" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lab_movimiento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"tipo" "movimiento_tipo" NOT NULL,
	"monto" numeric(12, 2) NOT NULL,
	"concepto" text NOT NULL,
	"notas" text,
	"fecha" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "lab_movimiento_monto_positivo" CHECK ("lab_movimiento"."monto" > 0)
);
--> statement-breakpoint
ALTER TABLE "laboratorio" ADD COLUMN "moroso" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "anuncio" ADD CONSTRAINT "anuncio_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lab_movimiento" ADD CONSTRAINT "lab_movimiento_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_anuncio_lab" ON "anuncio" USING btree ("lab_id");--> statement-breakpoint
CREATE INDEX "idx_lab_movimiento_lab_fecha" ON "lab_movimiento" USING btree ("lab_id","fecha");