CREATE TABLE "sede" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sede_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"nombre" text NOT NULL,
	"direccion" text NOT NULL,
	"localidad" text,
	"telefono" text,
	"email" text,
	"horarios" text,
	"principal" boolean DEFAULT false NOT NULL,
	"orden" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "sede" ADD CONSTRAINT "sede_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_sede_lab" ON "sede" USING btree ("lab_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_sede_lab_principal_active" ON "sede" USING btree ("lab_id") WHERE principal = true AND deleted_at IS NULL;