CREATE TYPE "public"."animal_sex" AS ENUM('macho', 'hembra', 'indeterminado');--> statement-breakpoint
CREATE TYPE "public"."order_type" AS ENUM('humana', 'veterinaria');--> statement-breakpoint
CREATE TYPE "public"."reproductive_status" AS ENUM('entero', 'castrado', 'esterilizado', 'gestante', 'lactante', 'desconocido');--> statement-breakpoint
CREATE TABLE "especie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "especie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" text NOT NULL,
	"nombre_cientifico" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paciente_animal" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "paciente_animal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"propietario_id" bigint NOT NULL,
	"especie_id" bigint NOT NULL,
	"raza_id" bigint,
	"nombre" text NOT NULL,
	"sexo" "animal_sex",
	"birth_date" date,
	"peso" numeric(8, 2),
	"color" text,
	"tamanio" text,
	"estado_reproductivo" "reproductive_status",
	"microchip" text,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "practice_referencia_especie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_referencia_especie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"practice_id" bigint NOT NULL,
	"especie_id" bigint NOT NULL,
	"range_low" numeric(20, 6),
	"range_high" numeric(20, 6),
	"unit" text,
	"reference_text" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "propietario" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "propietario_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"dni" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"phone" text,
	"email" text,
	"street_address" text,
	"city" text,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "raza" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "raza_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"especie_id" bigint NOT NULL,
	"nombre" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "veterinario" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "veterinario_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"matricula" text NOT NULL,
	"clinica" text,
	"phone" text,
	"email" text,
	"notes" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "patient_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "order_type" "order_type" DEFAULT 'humana' NOT NULL;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "animal_patient_id" bigint;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "veterinario_id" bigint;--> statement-breakpoint
ALTER TABLE "practice" ADD COLUMN "condicion_visibilidad" jsonb;--> statement-breakpoint
ALTER TABLE "unidad_medida" ADD COLUMN "opciones_predeterminadas" jsonb;--> statement-breakpoint
ALTER TABLE "paciente_animal" ADD CONSTRAINT "paciente_animal_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_animal" ADD CONSTRAINT "paciente_animal_propietario_id_propietario_id_fk" FOREIGN KEY ("propietario_id") REFERENCES "public"."propietario"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_animal" ADD CONSTRAINT "paciente_animal_especie_id_especie_id_fk" FOREIGN KEY ("especie_id") REFERENCES "public"."especie"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_animal" ADD CONSTRAINT "paciente_animal_raza_id_raza_id_fk" FOREIGN KEY ("raza_id") REFERENCES "public"."raza"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paciente_animal" ADD CONSTRAINT "paciente_animal_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_referencia_especie" ADD CONSTRAINT "practice_referencia_especie_practice_id_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_referencia_especie" ADD CONSTRAINT "practice_referencia_especie_especie_id_especie_id_fk" FOREIGN KEY ("especie_id") REFERENCES "public"."especie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "propietario" ADD CONSTRAINT "propietario_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "propietario" ADD CONSTRAINT "propietario_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raza" ADD CONSTRAINT "raza_especie_id_especie_id_fk" FOREIGN KEY ("especie_id") REFERENCES "public"."especie"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "veterinario" ADD CONSTRAINT "veterinario_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "veterinario" ADD CONSTRAINT "veterinario_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_especie_nombre" ON "especie" USING btree (lower("nombre"));--> statement-breakpoint
CREATE INDEX "idx_especie_active" ON "especie" USING btree ("active");--> statement-breakpoint
CREATE INDEX "idx_paciente_animal_lab" ON "paciente_animal" USING btree ("lab_id");--> statement-breakpoint
CREATE INDEX "idx_paciente_animal_propietario" ON "paciente_animal" USING btree ("propietario_id");--> statement-breakpoint
CREATE INDEX "idx_paciente_animal_especie" ON "paciente_animal" USING btree ("especie_id");--> statement-breakpoint
CREATE INDEX "idx_paciente_animal_nombre_trgm" ON "paciente_animal" USING gin (nombre gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_practice_ref_especie_unique" ON "practice_referencia_especie" USING btree ("practice_id","especie_id");--> statement-breakpoint
CREATE INDEX "idx_practice_ref_especie_practice" ON "practice_referencia_especie" USING btree ("practice_id");--> statement-breakpoint
CREATE INDEX "idx_practice_ref_especie_especie" ON "practice_referencia_especie" USING btree ("especie_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_propietario_lab_dni_active" ON "propietario" USING btree ("lab_id","dni") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_propietario_lastname_trgm" ON "propietario" USING gin (last_name gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_propietario_lab" ON "propietario" USING btree ("lab_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_raza_especie_nombre" ON "raza" USING btree ("especie_id",lower("nombre"));--> statement-breakpoint
CREATE INDEX "idx_raza_especie" ON "raza" USING btree ("especie_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_veterinario_lab_matricula_active" ON "veterinario" USING btree ("lab_id","matricula") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "idx_veterinario_lastname_trgm" ON "veterinario" USING gin (last_name gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_veterinario_lab" ON "veterinario" USING btree ("lab_id");--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_animal_patient_id_paciente_animal_id_fk" FOREIGN KEY ("animal_patient_id") REFERENCES "public"."paciente_animal"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_veterinario_id_veterinario_id_fk" FOREIGN KEY ("veterinario_id") REFERENCES "public"."veterinario"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_order_animal_patient" ON "order" USING btree ("animal_patient_id");--> statement-breakpoint
CREATE INDEX "idx_order_type" ON "order" USING btree ("order_type");