-- Resync de drift: captura en migraciones lo que ya estaba en el schema pero no en el manual.
-- Idempotente a propósito: en erqxxx algunas cosas ya existen (veterinaria_habilitada),
-- y las 2 tablas no; en una rama de dev nueva no existe nada. Seguro en ambos casos.
CREATE TABLE IF NOT EXISTS "lab_practice_config" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lab_practice_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lab_id" bigint NOT NULL,
	"practice_id" bigint NOT NULL,
	"methodology" text,
	"reference_value" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "practice_unidad_ref_especie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_unidad_ref_especie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"practice_unidad_id" bigint NOT NULL,
	"especie_id" bigint NOT NULL,
	"range_low" numeric(12, 4),
	"range_high" numeric(12, 4),
	"reference_text" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "laboratorio" ADD COLUMN IF NOT EXISTS "veterinaria_habilitada" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "practice_unidad" ADD COLUMN IF NOT EXISTS "range_low" numeric(12, 4);--> statement-breakpoint
ALTER TABLE "practice_unidad" ADD COLUMN IF NOT EXISTS "range_high" numeric(12, 4);--> statement-breakpoint
ALTER TABLE "practice_unidad" ADD COLUMN IF NOT EXISTS "reference_text" text;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lab_practice_config" ADD CONSTRAINT "lab_practice_config_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lab_practice_config" ADD CONSTRAINT "lab_practice_config_practice_id_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practice"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "practice_unidad_ref_especie" ADD CONSTRAINT "practice_unidad_ref_especie_practice_unidad_id_practice_unidad_id_fk" FOREIGN KEY ("practice_unidad_id") REFERENCES "public"."practice_unidad"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "practice_unidad_ref_especie" ADD CONSTRAINT "practice_unidad_ref_especie_especie_id_especie_id_fk" FOREIGN KEY ("especie_id") REFERENCES "public"."especie"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_lab_practice_config_unique" ON "lab_practice_config" USING btree ("lab_id","practice_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_pu_ref_especie_unique" ON "practice_unidad_ref_especie" USING btree ("practice_unidad_id","especie_id");
