-- Servicios dinámicos: reemplaza order_type enum por tabla servicio.
-- Idempotente: seguro re-ejecutar en cualquier entorno.

-- 1. Crear tabla servicio
CREATE TABLE IF NOT EXISTS "servicio" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "servicio_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "nombre" text NOT NULL,
  "slug" varchar(100) NOT NULL,
  "icono" text,
  "orden" integer DEFAULT 0 NOT NULL,
  "activo" boolean DEFAULT true NOT NULL,
  "usa_paciente_humano" boolean DEFAULT false NOT NULL,
  "usa_paciente_animal" boolean DEFAULT false NOT NULL,
  "usa_medico" boolean DEFAULT false NOT NULL,
  "usa_veterinario" boolean DEFAULT false NOT NULL,
  "usa_propietario" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "servicio" ADD CONSTRAINT "servicio_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_servicio_lab_slug" ON "servicio" USING btree ("lab_id","slug");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_servicio_lab_orden" ON "servicio" USING btree ("lab_id","orden");
--> statement-breakpoint

-- 2. Seed Humana + Veterinaria para cada lab existente (idempotente)
INSERT INTO "servicio" ("lab_id", "nombre", "slug", "icono", "orden", "activo", "usa_paciente_humano", "usa_paciente_animal", "usa_medico", "usa_veterinario", "usa_propietario")
SELECT l.id, 'Humana', 'humana', 'stethoscope', 0, true, true, false, true, false, false
FROM "laboratorio" l
WHERE NOT EXISTS (SELECT 1 FROM "servicio" s WHERE s.lab_id = l.id AND s.slug = 'humana');
--> statement-breakpoint
INSERT INTO "servicio" ("lab_id", "nombre", "slug", "icono", "orden", "activo", "usa_paciente_humano", "usa_paciente_animal", "usa_medico", "usa_veterinario", "usa_propietario")
SELECT l.id, 'Veterinaria', 'veterinaria', 'paw-print', 1, true, false, true, false, true, true
FROM "laboratorio" l
WHERE NOT EXISTS (SELECT 1 FROM "servicio" s WHERE s.lab_id = l.id AND s.slug = 'veterinaria');
--> statement-breakpoint

-- 3. Agregar servicio_id a order (nullable inicialmente)
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "servicio_id" bigint;
--> statement-breakpoint

-- 4. Migrar datos: mapear order_type al servicio correspondiente
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'order' AND column_name = 'order_type') THEN
    UPDATE "order" o
    SET servicio_id = s.id
    FROM "servicio" s
    WHERE s.lab_id = o.lab_id
      AND s.slug = o.order_type::text
      AND o.servicio_id IS NULL;
  END IF;
END $$;
--> statement-breakpoint

-- Para orders que no matchearon (edge case), asignar el servicio Humana del lab
UPDATE "order" o
SET servicio_id = (SELECT s.id FROM "servicio" s WHERE s.lab_id = o.lab_id AND s.slug = 'humana' LIMIT 1)
WHERE o.servicio_id IS NULL;
--> statement-breakpoint

-- 5. Hacer servicio_id NOT NULL
ALTER TABLE "order" ALTER COLUMN "servicio_id" SET NOT NULL;
--> statement-breakpoint

-- 6. FK de order.servicio_id
DO $$ BEGIN
 ALTER TABLE "order" ADD CONSTRAINT "order_servicio_id_servicio_id_fk" FOREIGN KEY ("servicio_id") REFERENCES "public"."servicio"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint

-- 7. Crear index para servicio_id en order
CREATE INDEX IF NOT EXISTS "idx_order_servicio" ON "order" USING btree ("servicio_id");
--> statement-breakpoint

-- 8. Dropear columna order_type y el enum
DROP INDEX IF EXISTS "idx_order_type";
--> statement-breakpoint
ALTER TABLE "order" DROP COLUMN IF EXISTS "order_type";
--> statement-breakpoint
DROP TYPE IF EXISTS "order_type";
--> statement-breakpoint

-- 9. Agregar servicio_id a preferencia_pdf (nullable — NULL = formato legacy/default)
ALTER TABLE "preferencia_pdf" ADD COLUMN IF NOT EXISTS "servicio_id" bigint;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "preferencia_pdf" ADD CONSTRAINT "preferencia_pdf_servicio_id_servicio_id_fk" FOREIGN KEY ("servicio_id") REFERENCES "public"."servicio"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_preferencia_pdf_servicio" ON "preferencia_pdf" USING btree ("lab_id","servicio_id");
