-- Entidades de Agua y efluentes: solicitantes y muestras.

CREATE TABLE IF NOT EXISTS "solicitante_agua" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solicitante_agua_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "nombre_apellido" text NOT NULL,
  "razon_social" text,
  "cuit" text,
  "domicilio" text,
  "localidad" text,
  "provincia" text,
  "telefono" text,
  "email" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "solicitante_agua" ADD CONSTRAINT "solicitante_agua_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_solicitante_agua_lab" ON "solicitante_agua" USING btree ("lab_id");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "muestra_agua" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "muestra_agua_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "lab_id" bigint NOT NULL,
  "solicitante_id" bigint NOT NULL,
  "fecha_toma" timestamp with time zone NOT NULL,
  "fecha_recepcion" timestamp with time zone NOT NULL,
  "tipo_muestra" text NOT NULL,
  "lugar_toma" text,
  "descripcion_punto" text,
  "direccion_punto" text,
  "localidad_punto" text,
  "motivo_analisis" text NOT NULL,
  "recipiente_adecuado" boolean DEFAULT false NOT NULL,
  "recipiente_esteril" boolean DEFAULT false NOT NULL,
  "conservacion_transporte" text,
  "temperatura_recepcion" numeric(5, 1),
  "volumen_recibido" text,
  "muestra_apta" boolean DEFAULT true NOT NULL,
  "observaciones_recepcion" text,
  "analisis_fisicoquimico" boolean DEFAULT false NOT NULL,
  "analisis_microbiologico" boolean DEFAULT false NOT NULL,
  "observaciones" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "muestra_agua" ADD CONSTRAINT "muestra_agua_lab_id_laboratorio_id_fk" FOREIGN KEY ("lab_id") REFERENCES "public"."laboratorio"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "muestra_agua" ADD CONSTRAINT "muestra_agua_solicitante_id_solicitante_agua_id_fk" FOREIGN KEY ("solicitante_id") REFERENCES "public"."solicitante_agua"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_muestra_agua_lab" ON "muestra_agua" USING btree ("lab_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_muestra_agua_solicitante" ON "muestra_agua" USING btree ("solicitante_id");
