-- Cotizaciones: catálogo de precios por práctica × obra social y documentos de cotización.
CREATE TYPE "public"."cotizacion_estado" AS ENUM('borrador', 'enviada', 'aceptada', 'rechazada', 'expirada');--> statement-breakpoint
CREATE TYPE "public"."cotizacion_tipo" AS ENUM('paciente', 'empresa');--> statement-breakpoint

CREATE TABLE "cotizacion_precio" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cotizacion_precio_id_seq"),
  "lab_id" bigint NOT NULL REFERENCES "laboratorio"("id") ON DELETE CASCADE,
  "practice_id" bigint NOT NULL REFERENCES "practice"("id") ON DELETE CASCADE,
  "insurer_id" bigint REFERENCES "insurer"("id") ON DELETE CASCADE,
  "precio" numeric(12,2) NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);--> statement-breakpoint

CREATE TABLE "cotizacion" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cotizacion_id_seq"),
  "lab_id" bigint NOT NULL REFERENCES "laboratorio"("id") ON DELETE CASCADE,
  "tipo" "cotizacion_tipo" NOT NULL,
  "estado" "cotizacion_estado" NOT NULL DEFAULT 'borrador',
  "patient_id" bigint REFERENCES "patient"("id") ON DELETE RESTRICT,
  "empresa_nombre" text,
  "empresa_cuit" text,
  "empresa_email" text,
  "empresa_telefono" text,
  "empresa_contacto" text,
  "insurer_id" bigint REFERENCES "insurer"("id") ON DELETE RESTRICT,
  "total_monto" numeric(12,2) NOT NULL DEFAULT '0',
  "validez_dias" integer NOT NULL DEFAULT 30,
  "observaciones" text,
  "created_by" uuid REFERENCES "auth"."users"("id"),
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  "deleted_at" timestamp with time zone
);--> statement-breakpoint

CREATE TABLE "cotizacion_item" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cotizacion_item_id_seq"),
  "cotizacion_id" bigint NOT NULL REFERENCES "cotizacion"("id") ON DELETE CASCADE,
  "practice_id" bigint REFERENCES "practice"("id") ON DELETE SET NULL,
  "practica_nombre" text NOT NULL,
  "precio_unitario" numeric(12,2) NOT NULL,
  "cantidad" integer NOT NULL DEFAULT 1,
  "subtotal" numeric(12,2) NOT NULL,
  "sort" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);--> statement-breakpoint

-- Unique indexes para cotizacion_precio (insurer_id nullable)
CREATE UNIQUE INDEX "idx_cotprecio_insurer" ON "cotizacion_precio" ("lab_id", "practice_id", "insurer_id") WHERE insurer_id IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_cotprecio_default" ON "cotizacion_precio" ("lab_id", "practice_id") WHERE insurer_id IS NULL;--> statement-breakpoint

-- Indexes de performance
CREATE INDEX "idx_cotprecio_lab" ON "cotizacion_precio" ("lab_id");--> statement-breakpoint
CREATE INDEX "idx_cotprecio_practice" ON "cotizacion_precio" ("practice_id");--> statement-breakpoint
CREATE INDEX "idx_cotizacion_lab" ON "cotizacion" ("lab_id");--> statement-breakpoint
CREATE INDEX "idx_cotizacion_estado" ON "cotizacion" ("estado");--> statement-breakpoint
CREATE INDEX "idx_cotizacion_patient" ON "cotizacion" ("patient_id");
