-- Catálogo de antibióticos (referencia global, independiente de unidad_medida)
CREATE TABLE antibiotico (
  id     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME antibiotico_id_seq),
  nombre text NOT NULL UNIQUE
);

-- Antibióticos configurados para el antibiograma de una práctica dada
CREATE TABLE practice_antibiograma (
  id             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME practice_antibiograma_id_seq),
  practice_id    bigint NOT NULL REFERENCES practice(id) ON DELETE CASCADE,
  antibiotico_id bigint NOT NULL REFERENCES antibiotico(id) ON DELETE RESTRICT,
  sort_order     integer NOT NULL DEFAULT 0,
  UNIQUE (practice_id, antibiotico_id)
);
CREATE INDEX idx_practice_antibiograma_practice ON practice_antibiograma(practice_id);

-- Resultados de antibiograma por línea de orden (S/I/R)
CREATE TABLE order_practice_antibiograma_result (
  id                   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_practice_antibiograma_result_id_seq),
  order_practice_id    bigint NOT NULL REFERENCES order_practice(id) ON DELETE CASCADE,
  antibiotico_id       bigint NOT NULL,
  antibiotico_snapshot text NOT NULL,
  resultado            text CHECK (resultado IN ('S', 'I', 'R')),
  recuento_ufc_ml      text,
  UNIQUE (order_practice_id, antibiotico_id)
);
CREATE INDEX idx_order_practice_abg_op ON order_practice_antibiograma_result(order_practice_id);
