-- Add standalone flag to practice table
ALTER TABLE practice ADD COLUMN IF NOT EXISTS standalone boolean NOT NULL DEFAULT true;

-- Mark existing children as non-standalone
UPDATE practice SET standalone = false WHERE parent_id IS NOT NULL;

-- M:N composition table
CREATE TABLE IF NOT EXISTS practice_composition (
  id                   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME practice_composition_id_seq),
  parent_practice_id   bigint NOT NULL REFERENCES practice(id) ON DELETE CASCADE,
  component_practice_id bigint NOT NULL REFERENCES practice(id) ON DELETE CASCADE,
  sort_order           integer NOT NULL DEFAULT 0,
  UNIQUE (parent_practice_id, component_practice_id)
);

CREATE INDEX IF NOT EXISTS idx_practice_composition_parent    ON practice_composition(parent_practice_id);
CREATE INDEX IF NOT EXISTS idx_practice_composition_component ON practice_composition(component_practice_id);

-- Migrate existing parent_id relationships
INSERT INTO practice_composition (parent_practice_id, component_practice_id, sort_order)
SELECT parent_id, id, 0
FROM practice
WHERE parent_id IS NOT NULL
ON CONFLICT DO NOTHING;
