-- ─── Multi-muestra para órdenes de agua/efluentes ────────────────────────────
-- Approach B: las prácticas se replican por muestra en order_practice.
-- Cada fila de order_muestra_agua = 1 muestra física del pedido.

CREATE TABLE IF NOT EXISTS order_muestra_agua (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_muestra_agua_id_seq),
  order_id      bigint NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
  muestra_agua_id bigint NOT NULL REFERENCES muestra_agua(id) ON DELETE RESTRICT,
  identificador text,
  sort_order    integer NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_muestra_agua_order ON order_muestra_agua(order_id);

-- Agregar FK a order_practice para vincular cada línea con su muestra
ALTER TABLE order_practice
  ADD COLUMN IF NOT EXISTS muestra_orden_id bigint REFERENCES order_muestra_agua(id) ON DELETE CASCADE;

-- Migrar órdenes existentes de agua: crear una fila en order_muestra_agua
-- por cada orden que ya tenía muestra_agua_id directo en la tabla order,
-- y apuntar todas sus líneas de práctica a esa fila.
DO $$
DECLARE
  rec RECORD;
  new_oma_id bigint;
BEGIN
  FOR rec IN
    SELECT id, muestra_agua_id
    FROM "order"
    WHERE muestra_agua_id IS NOT NULL
  LOOP
    INSERT INTO order_muestra_agua (order_id, muestra_agua_id, sort_order)
    VALUES (rec.id, rec.muestra_agua_id, 0)
    RETURNING id INTO new_oma_id;

    UPDATE order_practice
    SET muestra_orden_id = new_oma_id
    WHERE order_id = rec.id;
  END LOOP;
END $$;
