import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { sql } from 'drizzle-orm';
import { closeDb, getDb } from './client';
import { type NewPractice, practice } from './schema';

/**
 * Idempotent import of the NBU catalog generated by
 * practicas-migration/extract.py. Upserts by nbu_code: re-running only
 * updates changed rows, never duplicates. Reviewed dataset:
 * practicas-migration/nbu-dataset.json (1445 practices).
 */

interface DatasetRow {
  nbuCode: string;
  name: string;
  units: string | null;
  section: string | null;
  active: boolean;
  isSpecialAct: boolean;
  needsReview: boolean;
  notes: string;
}

const CHUNK = 500;

async function importNbu() {
  const path = join(process.cwd(), 'practicas-migration', 'nbu-dataset.json');
  const { summary, practices } = JSON.parse(readFileSync(path, 'utf-8')) as {
    summary: Record<string, unknown>;
    practices: DatasetRow[];
  };

  console.log('Dataset summary:', JSON.stringify(summary));
  console.log(`Importing ${practices.length} practices (upsert by nbu_code)...`);

  const db = getDb();
  const rows: NewPractice[] = practices.map((p) => ({
    nbuCode: p.nbuCode,
    name: p.name,
    units: p.units,
    section: p.section,
    active: p.active,
    isSpecialAct: p.isSpecialAct,
    notes: p.notes,
  }));

  let processed = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    await db
      .insert(practice)
      .values(chunk)
      .onConflictDoUpdate({
        target: practice.nbuCode,
        set: {
          name: sql`excluded.name`,
          units: sql`excluded.units`,
          section: sql`excluded.section`,
          active: sql`excluded.active`,
          isSpecialAct: sql`excluded.is_special_act`,
          notes: sql`excluded.notes`,
          updatedAt: sql`now()`,
        },
      });
    processed += chunk.length;
    console.log(`  upserted ${processed}/${rows.length}`);
  }

  const [{ count }] = await db.select({ count: sql<number>`count(*)::int` }).from(practice);
  console.log(`Done. practice table now has ${count} rows.`);
}

importNbu()
  .then(() => closeDb())
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error(err);
    await closeDb();
    process.exit(1);
  });
