/**
 * Aplica manualmente los cambios de schema multi-tenant a la BD existente.
 * Ejecutar UNA SOLA VEZ: npx tsx src/dev/apply-schema.ts
 */
import 'dotenv/config';
import postgres from 'postgres';

async function main() {
  const sql = postgres(process.env.DATABASE_URL!);

  console.log('Inspeccionando schema actual...');
  const cols = await sql`
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'user'
    ORDER BY ordinal_position
  `;
  console.log('Columnas actuales en public.user:', cols.map((c: Record<string, string>) => c.column_name).join(', '));

  const enumVals = await sql`
    SELECT enumlabel FROM pg_enum e
    JOIN pg_type t ON e.enumtypid = t.oid
    WHERE t.typname = 'user_role'
    ORDER BY e.enumsortorder
  `;
  console.log('Valores actuales de user_role enum:', enumVals.map((r: Record<string, string>) => r.enumlabel).join(', '));

  // ── 1. Crear tabla laboratorio si no existe ──────────────────────────────
  await sql`
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_lab') THEN
        CREATE TYPE estado_lab AS ENUM ('activo', 'suspendido', 'inactivo');
      END IF;
    END $$
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS laboratorio (
      id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "laboratorio_id_seq"),
      slug varchar(63) NOT NULL UNIQUE,
      legal_name text NOT NULL,
      short_name text,
      cuit text,
      street_address text,
      city text DEFAULT 'Santa Fe',
      province text DEFAULT 'Santa Fe',
      phone text,
      email text,
      signing_professional_name text,
      signing_professional_mp text,
      signing_signature_path text,
      logo_path text,
      estado estado_lab NOT NULL DEFAULT 'activo',
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    )
  `;
  console.log('✓ tabla laboratorio OK');

  // ── 2. Crear tabla preferencia_pdf si no existe ──────────────────────────
  await sql`
    CREATE TABLE IF NOT EXISTS preferencia_pdf (
      id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "preferencia_pdf_id_seq"),
      lab_id bigint NOT NULL REFERENCES laboratorio(id) ON DELETE CASCADE,
      fondo_path text,
      layout_config jsonb,
      margin_top integer NOT NULL DEFAULT 20,
      margin_bottom integer NOT NULL DEFAULT 20,
      margin_left integer NOT NULL DEFAULT 20,
      margin_right integer NOT NULL DEFAULT 20,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    )
  `;
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_preferencia_pdf_lab ON preferencia_pdf(lab_id)
  `;
  console.log('✓ tabla preferencia_pdf OK');

  // ── 3. Agregar lab_id a public.user (nullable para super) ────────────────
  const hasLabId = cols.some((c: Record<string, string>) => c.column_name === 'lab_id');
  if (!hasLabId) {
    await sql`ALTER TABLE "user" ADD COLUMN lab_id bigint REFERENCES laboratorio(id) ON DELETE RESTRICT`;
    console.log('✓ columna lab_id agregada a user');
  } else {
    // Asegurar que no tiene NOT NULL (puede que ya exista de una migración anterior)
    await sql`ALTER TABLE "user" ALTER COLUMN lab_id DROP NOT NULL`.catch(() => {});
    console.log('✓ lab_id ya existe en user');
  }

  // ── 4. Agregar 'super' al enum user_role ────────────────────────────────
  const hasSuper = enumVals.some((r: Record<string, string>) => r.enumlabel === 'super');
  if (!hasSuper) {
    await sql`ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'super'`;
    console.log("✓ 'super' agregado al enum user_role");
  } else {
    console.log("✓ 'super' ya existe en user_role");
  }

  // ── 5. Agregar lab_id a las otras tablas tenant-scoped (si no existen) ──
  const tenantTables = [
    { table: 'patient', column: 'lab_id' },
    { table: 'doctor', column: 'lab_id' },
    { table: 'ub_value', column: 'lab_id' },
    { table: 'order', column: 'lab_id' },
    { table: 'audit_log', column: 'lab_id' },
  ];

  for (const { table, column } of tenantTables) {
    const tableCols = await sql`
      SELECT column_name FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${table} AND column_name = ${column}
    `;
    if (tableCols.length === 0) {
      await sql.unsafe(`ALTER TABLE "${table}" ADD COLUMN lab_id bigint REFERENCES laboratorio(id) ON DELETE RESTRICT`);
      console.log(`✓ lab_id agregado a ${table}`);
    } else {
      console.log(`✓ lab_id ya existe en ${table}`);
    }
  }

  await sql.end();
  console.log('\n✓ Schema actualizado correctamente');
}

main().catch(async (e) => { console.error(e); process.exit(1); });
